name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck

      - name: Build R package
        run: |
          R CMD build .

      - name: Create release artifact name
        id: artifact
        run: |
          PKG_VERSION=$(grep -E '^Version:' DESCRIPTION | sed 's/Version:[[:space:]]*//g')
          PKG_NAME=$(grep -E '^Package:' DESCRIPTION | sed 's/Package:[[:space:]]*//g')
          echo "pkg_file=${PKG_NAME}_${PKG_VERSION}.tar.gz" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.artifact.outputs.pkg_file }}
          draft: false
          prerelease: false
          generate_release_notes: true
